eureka:
  client:
    service-url:
      defaultZone: http://192.168.0.111:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: 192.168.0.111
server:
  port: 8762

spring:
  application:
    name: eureka-client
